dist: xenial
services:
  - xvfb
language: python
python:
    - "3.7"
before_install:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry install
    - pip install codecov
script:
    - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
    - xvfb-run poetry run pytest tests
after_success:
    - codecov