language: python
python:
    - "3.7"
before_install:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry install
script:
    - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
    - poetry run pytest tests
    - pip install codecov
after_success:
    - codecov